export const BCRYPT_SALT_ROUNDS = 12;
export const SHA256_HEX_LENGTH = 64;

export const JWT_ACCESS_SECRET_KEY = 'JWT_ACCESS_SECRET';
export const JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET';
export const ACCESS_TOKEN_EXPIRES_KEY = 'ACCESS_TOKEN_EXPIRES';
export const REFRESH_TOKEN_EXPIRES_KEY = 'REFRESH_TOKEN_EXPIRES';
